name: dbt_build
on:
    schedule:
        - cron: '0 8 1 * *'
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    dbt_build:
        runs-on: ubuntu-latest

        steps:
            - name: repository checkout
              uses: actions/checkout@v4.2.2

            - name: python setup
              uses: actions/setup-python@v5.6.0
              with:
                python-version: '3.12'

            - name: dbt install requirements
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: profiles.yml create
              run: |
                mkdir -p ~/.dbt
                cat > ~/.dbt/profiles.yml << EOF
                nyc_taxi_trips:
                    target: prod
                    outputs:
                        prod:
                            type: duckdb
                            path: md:nyc_taxi_trips
                            token: "${{ secrets.MOTHERDUCK_TOKEN }}"
                            schema: prod
                            threads: 4
                EOF

            - name: dbt packages install
              run: |
                dbt deps

            - name: dbt source freshness run
              run: |
                dbt source freshness
              continue-on-error: true
              env:
                MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}

            - name: dbt seed run
              run: |
                dbt seed 
              env:
                MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}

            - name: dbt build run
              run: |
                dbt build 
              env:
                MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}